openapi: 3.0.0
info:
  title: Inventory App
  description: Application for storing JVM system properties of various hosts.
  license:
    name: Eclipse Public License - v 1.0
    url: https://www.eclipse.org/legal/epl-v10.html
  version: "1.0"
servers:
- url: http://localhost:{port}
  description: Simple Open Liberty.
  variables:
    port:
      description: Server HTTP port.
      default: "9080"
paths:
  /inventory/systems/{hostname}:
    get:
      summary: Get JVM system properties for particular host
      description: Retrieves and returns the JVM system properties from the system
        service running on the particular host.
      operationId: getPropertiesForHost
      parameters:
      - name: hostname
        in: path
        description: The host for whom to retrieve the JVM system properties for.
        required: true
        schema:
          type: string
        example: foo
      responses:
        404:
          description: Invalid hostname or the system service may not be running on
            the particular host.
          content:
            none: {}
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Properties'
  /inventory/systems:
    get:
      summary: List inventory contents.
      description: Returns the currently stored host:properties pairs in the inventory.
      operationId: listContents
      responses:
        200:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InventoryList'
  /inventory/properties:
    get:
      summary: Get JVM system properties.
      description: Returns the JVM system properties for the host running this service.
      operationId: getProperties
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Properties'
components:
  schemas:
    InventoryList:
      required:
      - systems
      type: object
      properties:
        systems:
          type: array
          items:
            $ref: '#/components/schemas/System'
        total:
          type: integer
      description: POJO that represents the inventory contents.
    Properties:
      type: object
      additionalProperties:
        type: string
    System:
      required:
      - hostname
      - properties
      type: object
      properties:
        hostname:
          type: string
        properties:
          type: object
          additionalProperties:
            type: string
      description: POJO that represents a single inventory entry.
